### ISSUE TITLE
Set Plain option in the Permalink Settings issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#135]
From the backend  :  Set Plain option in the Permalink Settings .

![image](https://user-images.githubusercontent.com/75515088/198505004-4609ba14-bd6b-4b2b-904f-e5a75f8fa07f.png)

Go to Food Dashboard .

From the filter option select one option.

Click on the filter option.

Here page is redirect to the other page.

![image](https://user-images.githubusercontent.com/75515088/198505802-bb6ad64f-c72c-417b-8fea-bdd363a01700.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

This issue is already fixed and below is the steps to check,

1.After set Plain permalink settings, **Go to Settings > Reading settings.**
2.Select **A static page > Homepage** as Foods.
3.Save the settings.

Now, you can check and verify the Food filter module on Food dashboard page.

**Point to be Noted:** It is working as same as WPEM.

**Comment by mistry-jignesh** [comment]
Performed above steps and verify the Food filter module on Food dashboard page.

Now this issue is working fine . So I closed the issue.
