### ISSUE TITLE
Food form field -Term Checklist, Term Multiselect and Term Select fields type not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpfoodmanager/wp-food-manager#161]
Food form field **-Term Checklist, Term Multiselect and Term Select** fields type not working.

![image](https://user-images.githubusercontent.com/75515088/202363824-626a12d4-178c-4c25-bc4c-90cd7afec6be.png)

Selected values not display on the details page.

![image](https://user-images.githubusercontent.com/75515088/202363996-83912f03-dff5-4562-92f4-0b8bd316935c.png)

**Comment by kushang-tailor** [comment]
Hello @mistry-jignesh ,

I have removed this 3 field types from the Food forms and set the defaults. Because We have already display this 3 field types output on frontend. Please check the below Screenshot...
![image](https://user-images.githubusercontent.com/25924876/204709965-fd5d0856-6fc7-41f7-b822-add3aa8c07bf.png)

**Comment by mistry-jignesh** [comment]
As per @kushang-tailor - Removed this 3 field types from the Food forms and set the defaults. Because we have already display this 3 field types output on frontend. So now this issue is resloved & working properly.

So I closed the issue.
