### ISSUE TITLE
Need to check chosen need or not ? or we can use suggest from wordpress

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#340]
Need to check chosen need or not ? or we can use suggest from wordpress

https://vulgarisoip.com/jquerysuggest-an-alternative-jquery-based-autocomplete-library/#comment-7228
<img width="1597" alt="Screenshot 2023-03-03 at 09 27 20" src="https://user-images.githubusercontent.com/15089059/222670046-09423436-60f3-4729-9349-043d138cd77f.png">

**Comment by vry-kvl** [comment]
@ashokdudhat sir, If we will use suggest in comparison to chosen then suggest is not that way what we are supposed.

I searched suggest.js jquery-ui in Google and it will go to https://jqueryui.com/autocomplete/. and autocomplete is not like multiple-selection types.

Autocomplete screenshot - 

<img width="439" alt="image" src="https://user-images.githubusercontent.com/119648390/234530462-713cbbd0-aaed-4679-99e8-7e889c6ec4f5.png">
This is like a search box.

---------------------------------------------

If we will use select2 instead of chosen but it will also be a third-party js or we need to make a custom but it will very time-consuming change.

**Comment by krinaydhanani** [comment]
As per Keval suggestion we should go with chosen js. So I am going to close this issue.
