### ISSUE TITLE
Topping description is not displaying

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#360]
If we create topping then the description is not displaying in admin side

![image](https://user-images.githubusercontent.com/121149500/225826277-e54a7885-813e-4861-a05a-ec912b9273f0.png)
![image](https://user-images.githubusercontent.com/121149500/225826398-e4557f63-65af-4ab3-9067-b2c093974b10.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - You are right but, In this case, we don't need to save the description, because of overwritten multiple times of description. Suppose Food 1 has topping-xyz and its description is 'lorem ipsum' and then the second food name Food 2 has also topping-xyz and its description is 'lorem ipsum test' which is not the same compared to the food 1 topping.

We have just connected the terms to the post type which is useful for our future pieces of stuff.

**Comment by patel-nimesh** [comment]
As per the developer comment it is not necessary So I am closing this issue
