### ISSUE TITLE
General : Need to add more default value of the Ingredient

### ISSUE THREAD

**Issue by ashokdudhat** [wpfoodmanager/wp-food-manager#396]
Currently we have the following list of Ingredients

'food_manager_ingredient' => array(
				'Vegetables',
				'Spices and Herbs',
				'Cereals and Pulses',
				'Meat',
				'Seafood',
			),

**These are the essential six staples to always have on hand.**

- Salt
- Pepper
- Olive oil
- Vegetable oil
- All-purpose flour
- Granulated sugar
- Vegetables
- Spices and Herbs
- Cereals and Pulses

Ref:

https://www.allrecipes.com/article/the-perfect-pantry/
https://www.soupersage.com/blog/30-most-popular-recipe-ingredients-2019/
https://www.webstaurantstore.com/article/22/food-allergy-overview.html

**Comment by vry-kvl** [comment]
@ashokdudhat - I have added : 
-------
- Salt
- Pepper
- Olive oil
- Vegetable oil
- Granulated sugar
- Vegetable oil
-------
And In the previous code already added :
-------
- Vegetables
- Spices and Herbs
- Cereals and Pulses
- Meat
- Seafood
-------
So, we have a total of 11 default Ingredient :
-------
1. Salt
2. Pepper
3. Olive oil
4. Vegetable oil
5. Granulated sugar
6. Vegetable oil
7. Vegetables
8. Spices and Herbs
9. Cereals and Pulses
10. Meat
11. Seafood

1 ingredient I Have not added the name as All-purpose flour. This is not usable. we can add a specific flour like :

- Corn flour
- Bread flour aka bakers flour
- Cake flour

That's why, I had not added All-purpose flour.

**Comment by patel-nimesh** [comment]
Now below 9 are the default Ingredients when install WPFM Plugin

![image](https://user-images.githubusercontent.com/121149500/228128011-f6156888-5dbf-432b-9dcf-f78f8fae1bd7.png)
