### ISSUE TITLE
Frontside edit food in console gives error

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#404]
Frontside edit food in console gives error

![image](https://user-images.githubusercontent.com/121149500/229494322-c32a52de-88e6-4caa-801c-fb5c7c2b92aa.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - I had discussed this with @krinaydhanani and decided that this is a non-break bug, which means that it gives an error but our plugin didn't have any functionality break-out. Also, this console error happens just because we append the HTML on the click of the +Add toppings button, and in HTML it will class contain '%%repeated-option-index%%' this keyword which has %, it is a special character and that's why jQuery gives an error because it's still not appended.

Soo This bug moved to the next milestone as per the discussion with @krinaydhanani.

**Comment by patel-nimesh** [comment]
Now No console error is displaying on edit food page
