### ISSUE TITLE
Admin : if topping price is not provided from admin side it gives console error

### ISSUE THREAD

**Issue by MahendraShiyal** [wpfoodmanager/wp-food-manager#410]
Admin : Add food : if topping price is not provided from back end (admin side) it gives console error . 

![image](https://user-images.githubusercontent.com/126650948/232446949-56556bb1-1ff2-4dd0-9fdd-529aa035b27a.png)

**Comment by vry-kvl** [comment]
@MahendraShiyal - I had discussed this with @krinaydhanani and decided that for the admin there is no restriction to add food but from the front end is. because the field editor and restrictions required or not it is only for the other users who have to add food and list their food.

Please can you verify it?

**Comment by vry-kvl** [comment]
@MahendraShiyal - Please verify it.
