### ISSUE TITLE
Admin : If we remove any field then it's value should be remove from database

### ISSUE THREAD

**Issue by patel-nimesh** [wpfoodmanager/wp-food-manager#436]
In the admin side If we remove any field then its value should be removed from database.

We can do as when delete any field we can show notice like "deleting this field will remove your data related to this field"

![image](https://user-images.githubusercontent.com/121149500/233034684-6268afe1-7a95-4c77-b4ce-a2c9b9ff695f.png)

**Comment by vry-kvl** [comment]
@patel-nimesh - The data is not deleted on remove the field in the field editor, It will remove on uninstall if delete data on uninstall is on.

Suppose 50 foods have a test_xyz field and the user deleted that field by mistake then the user has to re-enter the data in all of the food. that's why we are not removing data on the remove of field.

Also, I have discussed this point with @ashokdudhat sir.
Soo, there is nothing changes in this bug.

**Comment by patel-nimesh** [comment]
As per the developer @vry-kvl comment data will not be from the database. When user selects Delete WP Food Manager data when the plugin is deleted. Once removed, this data cannot be restored then it will remove the data from the database.
